### PR TITLE
Properly support non future impl traits

### LINKED ISSUE #35: Support non-Future `impl Trait` return types
Currently, [the erased trait always returns `-> Pin<Box<dyn $bounds>>`](https://github.com/spastorino/dynosaur/blob/main/dynosaur_derive/src/expand.rs#L167-L202).

This does not work with traits which do not have a blanket `impl SomeTrait for Pin<Box<dyn SomeTrait>>`.

For example, returning an `impl Iterator` currently fails:

```rust
#[dynosaur::dynosaur(DynSomeTrait)]
trait SomeTrait {
    fn get_iter(&mut self) -> impl Iterator<Item = u8> + '_;
}

struct MyImpl([u8; 4]);

impl SomeTrait for MyImpl {
    fn get_iter(&mut self) -> impl Iterator<Item = u8> + '_ {
        return self.0.into_iter();
    }
}

fn main() {
    let mut st = DynSomeTrait::boxed(MyImpl([3,2,4,1]));
    for x in st.get_iter() {
        println!("{}", x);
    }
}
```

produces the following:

```
error[E0226]: only a single explicit lifetime bound is permitted
 --> src/main.rs:1:1
  |
1 | #[dynosaur::dynosaur(DynSomeTrait)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the attribute macro `dynosaur::dynosaur` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: `Pin<Box<dyn Iterator<Item = u8>>>` is not an iterator
 --> src/main.rs:1:1
  |
1 | #[dynosaur::dynosaur(DynSomeTrait)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `Pin<Box<dyn Iterator<Item = u8>>>` is not an iterator
  |
  = help: the trait `Iterator` is not implemented for `Pin<Box<dyn Iterator<Item = u8>>>`

Some errors have detailed explanations: E0226, E0277.
For more information about an error, try `rustc --explain E0226`.
error: could not compile `testdyno` (bin "testdyno") due to 2 previous errors
```

Note: there's also an unrelated lifetime error due to the `+ '_` bound. The key bit is "`Pin<Box<dyn Iterator<Item = u8>>` is not an iterator" piece.

### PR DESCRIPTION
**Pull request by spastorino**
r? @tmandry

Closes #35

### CODE REVIEW

File: dynosaur_derive/src/expand.rs [hunk 1]
```diff
@@ -148,6 +138,19 @@ pub(crate) fn expand_sig_ret_ty_to_pin_box(sig: &mut Signature) {
     sig.output = parse_quote! { #arrow ::core::pin::Pin<Box<dyn #ret + 'dynosaur>> };
 }
 
+pub(crate) fn expand_sig_ret_ty_to_box(sig: &mut Signature) {
+    let (arrow, ret) = expand_arrow_ret_ty(sig);
+    if let Some(asyncness) = sig.asyncness.take() {
+        sig.fn_token.span = asyncness.span;
```
Comment (tmandry) [inline dynosaur_derive/src/expand.rs:144]: I've seen this in a few places in the code and don't understand why we do it.

File: dynosaur_derive/src/expand.rs [hunk 2]
```diff
@@ -148,6 +138,19 @@ pub(crate) fn expand_sig_ret_ty_to_pin_box(sig: &mut Signature) {
...
+    }
+
+    if has_lifetime_bound(sig) {
```
Comment (tmandry) [inline dynosaur_derive/src/expand.rs:147]: Seems like a mild sign of inconsistent layering that the caller also checks this condition before calling the function, but it's okay to leave it.

File: dynosaur_derive/src/lib.rs [hunk 3]
```diff
@@ -333,6 +340,26 @@ fn mk_dyn_struct_impl_item(struct_ident: &Ident, item_trait: &ItemTrait) -> Toke
...
                         }
+                    } else if is_rpit(&sig) {
+                        let ret = expand_ret_ty(&sig);
+
+                        if has_lifetime_bound(&sig) {
+                            quote! {
+                                #sig {
+                                    let ret: Box<dyn #ret> = self.ptr.#ident(#(#args),*);
+                                    let ret: Box<dyn #ret> = unsafe { ::core::mem::transmute(ret) };
+                                    ret
```
Comment (tmandry) [inline dynosaur_derive/src/lib.rs:351]: This doesn't make sense, is it exercised anywhere? I would expect it to be exercised by non-future-impl-traits.rs above, but the code there doesn't match this code, so not sure what's going on.

In any case I think we want `'_` in both cases; in other words, there's no need for this if/else to exist.

File: dynosaur_derive/src/expand.rs (hunk 1 above)
Comment (spastorino) [reply dynosaur_derive/src/expand.rs:144]: Given `async fn foo()`, we do `asyncness.take()` to remove the async part of the fn. Now we have `fn foo() -> impl Future<Output=()>` and effectively the span of the fn keyword in the new function is the span of the async keyword of the old function.

File: dynosaur_derive/src/expand.rs (hunk 2 above)
Comment (spastorino) [reply dynosaur_derive/src/expand.rs:147]: The caller doesn't check to call this function, it checks before to call it, to see if we need to expand input args or not. This is about the return type.
Anyway it may need to be structured a little but better maybe 😁

File: dynosaur_derive/src/lib.rs (hunk 3 above)
Comment (spastorino) [reply dynosaur_derive/src/lib.rs:351]: Yes it is. The Iterator example would be affected.
We have `Iterator<Item=u8> + '_`. `has_lifetime_bound` returns true and in this case, we just do the `#ret` version. `#ret` already includes '_ as bound so it would give you back `Iterator<Item=u8> + '_` which is what we want.

If we were going with the `#ret + '_` we would end with `Iterator<Item=u8> + '_ + '_` which is wrong.
This is actually the point and why `has_lifetime_bound` exists.

File: dynosaur_derive/src/expand.rs (hunk 1 above)
Comment (tmandry) [reply dynosaur_derive/src/expand.rs:144]: Why not make it the span of the `fn` keyword of the old function?

File: dynosaur_derive/src/lib.rs (hunk 3 above)
Comment (tmandry) [reply dynosaur_derive/src/lib.rs:351]: Ah, I suspect this won't work if the bound is anything other than `'_` then. If it were `'a` you would end up with an error.

Replacing the bound with `'_` should always work though.

File: dynosaur_derive/src/expand.rs (hunk 2 above)
Comment (tmandry) [reply dynosaur_derive/src/expand.rs:147]: I realize that, I just think it's a smell that it gets checked at two different levels of abstraction. Not a big deal though, I know proc macros can get messy like this!

File: dynosaur_derive/src/expand.rs (hunk 1 above)
Comment (spastorino) [reply dynosaur_derive/src/expand.rs:144]: We should try to address this in a followup as this is preexisting anyway. We're doing the same in `expand_sig_ret_ty_to_rpit`

File: dynosaur_derive/src/expand.rs (hunk 2 above)
Comment (spastorino) [reply dynosaur_derive/src/expand.rs]: This issue doesn't exist anymore and neither this function. The code is simpler now.

File: dynosaur_derive/src/lib.rs (hunk 3 above)
Comment (spastorino) [reply dynosaur_derive/src/lib.rs]: Fixed

File: dynosaur_derive/src/expand.rs [hunk 4]
```diff
@@ -201,7 +274,15 @@ fn expand_arrow_ret_ty(sig: &Signature) -> (RArrow, TokenStream) {
         }
         (false, ReturnType::Type(arrow, ret)) => {
             if let Type::ImplTrait(TypeImplTrait { bounds, .. }) = &**ret {
-                return (*arrow, quote!(#bounds));
+                let mut ret_bounds: Punctuated<&TypeParamBound, Token![+]> = Punctuated::new();
+
+                for bound in bounds {
```
Comment (tmandry) [inline dynosaur_derive/src/expand.rs:279]: Why filter out lifetimes here?

File: dynosaur_derive/src/expand.rs [hunk 5]
```diff
@@ -148,6 +135,14 @@ pub(crate) fn expand_sig_ret_ty_to_pin_box(sig: &mut Signature) {
     sig.output = parse_quote! { #arrow ::core::pin::Pin<Box<dyn #ret + 'dynosaur>> };
 }
 
+pub(crate) fn expand_sig_ret_ty_to_box(sig: &mut Signature) {
+    let (arrow, ret) = expand_arrow_ret_ty(sig);
+    if let Some(asyncness) = sig.asyncness.take() {
+        sig.fn_token.span = asyncness.span;
+    }
+    sig.output = parse_quote! { #arrow Box<dyn #ret + '_> };
```
Comment (tmandry) [inline dynosaur_derive/src/expand.rs:143]: The lifetime should work the same as in the pin_box case. If there's a single lifetime as in the current test we can simplify it all to `'_`, but otherwise we need the full `'dynosaur` thing. The return type can capture all input lifetimes, we can't assume it captures only the self lifetime (which `'_` would do).. we have to be very careful here because the unsafe lifetime extension is not checked by the compiler.

File: dynosaur/tests/pass/non-future-impl-traits.rs [hunk 6]
```diff
@@ -0,0 +1,19 @@
+#[dynosaur::dynosaur(DynSomeTrait)]
```
Comment (tmandry) [inline dynosaur/tests/pass/non-future-impl-traits.rs:1]: Let's add a test with a method that includes multiple input lifetimes

File: dynosaur_derive/src/expand.rs (hunk 1 above)
Comment (tmandry) [reply dynosaur_derive/src/expand.rs:141]: Doing it in a followup is fine

**Review by tmandry — CHANGES_REQUESTED** [review]

File: dynosaur_derive/src/expand.rs (hunk 4 above)
Comment (spastorino) [reply dynosaur_derive/src/expand.rs:280]: This is the return type, we filter and at the end use the `'dynosaur` one

**Review by tmandry — APPROVED** [review]
