### PR TITLE
Properly handle functions that do not return RPITs

### LINKED ISSUE #39: Support traits with non-async, non-impl Trait fns
Currently, the macro panics on traits with additional fns that are not async and don't have impl Trait on their return type:
```rust
#[dynosaur::dynosaur(DynJobQueue)] // error: custom attribute panicked
pub trait JobQueue {
    fn len(&self) -> usize;
    async fn dispatch(&self);
}
```

### PR DESCRIPTION
**Pull request by spastorino**
r? @tmandry 

Closes #39

### CODE REVIEW

File: dynosaur_derive/src/lib.rs [hunk 1]
```diff
@@ -185,72 +184,92 @@ pub fn dynosaur(
...
-                quote! {
-                    const #ident #generics: #ty = <Self as #trait_ident #trait_generics>::#ident;
+/// Remove Self: Sized fns
+fn dyn_compatible_items(item_trait_items: &[TraitItem]) -> impl Iterator<Item = &TraitItem> {
+    item_trait_items
+        .iter()
+        .filter_map(|trait_item| match trait_item {
+            TraitItem::Fn(trait_item_fn) if has_where_self_sized(&trait_item_fn.sig) => None,
+            _ => Some(trait_item),
+        })
```
Comment (tmandry) [inline dynosaur_derive/src/lib.rs:212]:
```suggestion
        .filter(|trait_item| match trait_item {
            TraitItem::Fn(trait_item_fn) if has_where_self_sized(&trait_item_fn.sig) => false,
            _ => true,
        })
```

File: dynosaur_derive/src/lib.rs [hunk 2]
```diff
@@ -185,72 +184,92 @@ pub fn dynosaur(
...
+                    } else {
+                        quote! {
+                            #sig {
+                                <Self as #trait_ident #trait_generics>::#ident(#(#args),*)
+                            }
+                        }
+                    }
+                }
+                TraitItem::Type(TraitItemType {
+                    ident, generics, .. }) => {
```
Comment (tmandry) [inline dynosaur_derive/src/lib.rs:260]:
```suggestion
                TraitItem::Type(TraitItemType { ident, generics, .. }) => {
```

File: dynosaur_derive/src/lib.rs [hunk 3]
```diff
@@ -364,53 +369,62 @@ fn mk_dyn_struct_impl_item(struct_ident: &Ident, item_trait: &ItemTrait) -> Toke
...
-                        type #ident #impl_generics = #ident #ty_generics #where_clause;
+                        #sig {
+                            self.ptr.#ident(#(#args),*)
+                        }
                     }
                 }
-        )
+            }
+            TraitItem::Type(TraitItemType {
+                ident, generics, .. }) => {
```
Comment (tmandry) [inline dynosaur_derive/src/lib.rs:420]:
```suggestion
            TraitItem::Type(TraitItemType { ident, generics, .. }) => {
```

**Review by tmandry — APPROVED** [review]
