### PR TITLE
Properly generate unrecheable code for non async fns

### LINKED ISSUE #55: `where Self: Sized` exclusion not working with `trait_variant` support
Using cargo script for brevity:

```rust
#!/usr/bin/env -S cargo +nightly -Zscript
---cargo
[package]
edition = "2021"
[dependencies]
dynosaur = "0.1.3"
trait-variant = "0.1.2"
---

#[trait_variant::make(Run: Send)]
#[dynosaur::dynosaur(DynLocalRun = dyn LocalRun)]
#[dynosaur::dynosaur(DynRun = dyn Run)]
pub trait LocalRun {
    async fn new() -> std::io::Result<Self>
    where
        Self: Sized;

    async fn run(&mut self) -> std::io::Result<()>;
}

fn main(){}
```

Gives compile error:

```
error[E0277]: `()` is not a future
  --> /home/cdruid/.cargo/target/e4/57393f8231c91d/script.rs:11:1
   |
11 | #[trait_variant::make(Run: Send)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `()` is not a future
   |
   = help: the trait `Future` is not implemented for `()`
```

Peeking at the expansion, it looks like it's coming from:

```rust
impl<'dynosaur_struct> Run for DynRun<'dynosaur_struct> {
    fn new()
        ->
            impl ::core::future::Future<Output = std::io::Result<Self>> +
            Send where Self: Sized {
        ::core::panicking::panic("internal error: entered unreachable code")
    }
```

I think the typical workarounds here are either to use `async fn new()` (currently used for the `!Send` case) or `let fut: ::core::pin::Pin<Box<dyn ::core::future::Future<Output = std::io::Result<Self>> + 'static + Send>> = panic!(); fut` (which I believe was used in the original implementation)

### PR DESCRIPTION
**Pull request by spastorino**
r? @tmandry 

Fixes #55

### CODE REVIEW

File: dynosaur_derive/src/sig.rs [hunk 1]
```diff
@@ -38,7 +38,7 @@ pub(crate) fn is_rpit(sig: &Signature) -> bool {
     match sig {
         Signature {
             asyncness: Some(_), ..
-        } => true,
+        } => false,
```
Comment (spastorino) [inline dynosaur_derive/src/sig.rs:41]: This doesn't introduce any regression, as `is_rpit` is always checked after checking `is_async`. The new semantics of the function makes more sense, as this is true just when there's an explicit rpit showing up and `is_async` would check the asyncness and if the return type is impl Future.

**Comment by tmandry** [comment]
It looks like this doesn't fix the case in #55 where it's an async fn with Self: Sized that fails; we should do this for those as well. The reason it fails is that in the dyn struct impl we convert the async fn to an RPIT.

**Comment by spastorino** [comment]
For the record:

```rust
trait Foo {}

#[dynosaur::dynosaur(DynMyTrait)]
trait MyTrait {
    fn foo(&mut self) -> impl Foo
    where Self: Sized;
}
```

Doesn't work as `Box<dyn Foo>` does not implement `Foo` :/.

**Comment by tmandry** [comment]
Oh yeah, I was thinking about that earlier but forgot to mention it here. Meh.
